#!/bin/bash
USER=<git_username>
PASSWORD=<git_password>
DIR=bitbucket.org/<git_username>/<git_project>.git

#1
sleep 1
echo "change directory <app_directory>"
cd <app_directory>

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR

#2
sleep 1
echo "change directory /home/andre/lhp-backend2/"
cd /home/andre/lhp-backend2/

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR

#3
sleep 1
echo "change directory /home/andre/lhp-backend3/"
cd /home/andre/lhp-backend3/

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR

#4
sleep 1
echo "change directory /<app_directory>"
cd /<app_directory>

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR


#5
sleep 1
echo "change directory /home/andre/lhp-backend5/"
cd /home/andre/lhp-backend5/

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR

#6
sleep 1
echo "change directory /home/andre/lhp-backend6/"
cd /home/andre/lhp-backend6/

echo "running script :"
git pull https://$USER:$PASSWORD@$DIR
